# Generated by Django 5.1.4 on 2025-01-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='tittle',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
