# Generated by Django 5.1.4 on 2025-01-29 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_lawyer_age'),
        ('clientapp', '0003_messages_tittle'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientapp.clients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.lawyer'),
        ),
    ]
