# Generated by Django 5.1.4 on 2025-01-30 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_messages_client_alter_messages_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='messages',
        ),
    ]
