# Generated by Django 5.0.6 on 2025-01-31 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_lawyer_age'),
        ('clientapp', '0006_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='lid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.lawyer'),
            preserve_default=False,
        ),
    ]
