# Generated by Django 5.1.5 on 2025-02-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0007_clients_lid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='client',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
    ]
