# Generated by Django 5.1.5 on 2025-02-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_rename_tittle_messages_title_remove_messages_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='msg',
        ),
    ]
