# Generated by Django 5.1.5 on 2025-02-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0009_rename_message_messages_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='cname',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
