# Generated by Django 5.1.5 on 2025-02-05 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0010_messages_cname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='cname',
        ),
        migrations.AddField(
            model_name='messages',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientapp.clients'),
            preserve_default=False,
        ),
    ]
