# Generated by Django 5.1.5 on 2025-02-07 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_lawyer_age'),
        ('clientapp', '0011_remove_messages_cname_messages_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='lawyer_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.lawyer'),
            preserve_default=False,
        ),
    ]
