# Generated by Django 5.1.5 on 2025-03-01 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0012_messages_lawyer_name'),
        ('userapp', '0052_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='case_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.clients')),
            ],
        ),
    ]
