# Generated by Django 5.1.4 on 2025-01-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_lawyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='phone_number',
        ),
    ]
