# Generated by Django 5.1.4 on 2025-01-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_lawyer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
