# Generated by Django 5.1.5 on 2025-02-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
