# Generated by Django 5.1.5 on 2025-02-27 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_education_options'),
        ('userapp', '0051_user_appointment_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_experience',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.case_categories'),
            preserve_default=False,
        ),
    ]
