# Generated by Django 5.1.5 on 2025-02-27 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_work_experience_type'),
        ('userapp', '0051_user_appointment_lawyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_experience',
            name='type',
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='Specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.case_categories'),
        ),
    ]
