# Generated by Django 5.1.4 on 2024-12-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attorneys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='image/')),
            ],
        ),
    ]
