# Generated by Django 5.1.4 on 2024-12-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_attorneys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=20)),
                ('discription', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='attorneys',
            name='profession',
            field=models.CharField(max_length=30),
        ),
    ]
