# Generated by Django 5.1.4 on 2024-12-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_client_review_alter_attorneys_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_review',
            name='image',
            field=models.FileField(default='default_image.png', upload_to='image/'),
            preserve_default=False,
        ),
    ]
