# Generated by Django 5.1.4 on 2024-12-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_client_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='image/')),
                ('tittle', models.CharField(max_length=30)),
                ('discription', models.CharField(max_length=100)),
            ],
        ),
    ]
