# Generated by Django 5.1.4 on 2024-12-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_blog_discription_alter_blog_tittle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types_Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=20)),
                ('Point1', models.CharField(max_length=20)),
                ('Point2', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='image/')),
            ],
        ),
    ]
