# Generated by Django 5.1.4 on 2024-12-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_types_law'),
    ]

    operations = [
        migrations.RenameField(
            model_name='types_law',
            old_name='image',
            new_name='law_image',
        ),
        migrations.RenameField(
            model_name='types_law',
            old_name='tittle',
            new_name='law_tittle',
        ),
    ]
