# Generated by Django 5.1.4 on 2024-12-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_rename_image_types_law_law_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types_law',
            name='Point1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='types_law',
            name='Point2',
            field=models.CharField(max_length=100),
        ),
    ]
