# Generated by Django 5.1.4 on 2024-12-20 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_types_law_point1_alter_types_law_point2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types_law',
            name='law_image',
        ),
    ]
