# Generated by Django 5.1.4 on 2024-12-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_remove_types_law_law_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='types_law',
            name='detail1',
            field=models.CharField(default=1, max_length=550),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='types_law',
            name='detail2',
            field=models.CharField(default=1, max_length=550),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='types_law',
            name='law_image',
            field=models.FileField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='types_law',
            name='Point1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='types_law',
            name='Point2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='types_law',
            name='law_tittle',
            field=models.CharField(max_length=50),
        ),
    ]
