# Generated by Django 5.1.4 on 2024-12-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_types_law_detail1_types_law_detail2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types_law',
            name='Point2',
        ),
    ]
