# Generated by Django 5.1.4 on 2024-12-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_remove_types_law_point2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types_law',
            name='detail2',
        ),
        migrations.RemoveField(
            model_name='types_law',
            name='law_image',
        ),
    ]
