# Generated by Django 5.1.4 on 2024-12-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_remove_types_law_detail2_remove_types_law_law_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='discription',
        ),
        migrations.AddField(
            model_name='blog',
            name='des',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
