# Generated by Django 5.1.4 on 2024-12-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_remove_blog_discription_blog_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det', models.CharField(max_length=200)),
                ('law_title', models.CharField(max_length=50)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.types_law')),
            ],
        ),
    ]
