# Generated by Django 5.1.4 on 2024-12-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_practice_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_categories', models.CharField(max_length=50)),
            ],
        ),
    ]
