# Generated by Django 5.1.4 on 2024-12-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_case_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_studies_image', models.FileField(upload_to='image/')),
                ('case_studies_title', models.DateField(max_length=200)),
            ],
        ),
    ]
