# Generated by Django 5.1.4 on 2024-12-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_case_studies'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_studies',
            name='case_studies_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='case_studies_title',
            field=models.CharField(max_length=200),
        ),
    ]
