# Generated by Django 5.1.4 on 2024-12-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_case_studies_case_studies_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_studies',
            name='case_studies_date',
            field=models.CharField(max_length=20),
        ),
    ]
