# Generated by Django 5.1.4 on 2024-12-25 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_alter_case_studies_case_studies_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_studies',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.case_categories'),
            preserve_default=False,
        ),
    ]
