# Generated by Django 5.1.4 on 2024-12-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_case_studies_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_studies',
            name='case_studies_image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
