# Generated by Django 5.1.4 on 2024-12-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_alter_case_studies_case_studies_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='case_studies',
        ),
    ]
