# Generated by Django 5.1.4 on 2024-12-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_delete_case_studies'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_new', models.CharField(max_length=15)),
            ],
        ),
    ]
