# Generated by Django 5.1.4 on 2024-12-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
