# Generated by Django 5.1.4 on 2024-12-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_delete_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_studies_tittle', models.CharField(max_length=50)),
                ('case_studies_date', models.CharField(max_length=200)),
                ('case_studies_image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.RenameField(
            model_name='types_law',
            old_name='Point1',
            new_name='Point',
        ),
        migrations.RenameField(
            model_name='types_law',
            old_name='detail1',
            new_name='detail',
        ),
    ]
