# Generated by Django 5.1.4 on 2024-12-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_case_studies_rename_point1_types_law_point_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='types_law',
            old_name='Point',
            new_name='point',
        ),
    ]
