# Generated by Django 5.1.4 on 2024-12-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_rename_point_types_law_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_studies',
            name='case_studies_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='case_studies_tittle',
            field=models.CharField(max_length=100),
        ),
    ]
