# Generated by Django 5.1.4 on 2024-12-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0028_alter_case_studies_case_studies_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_studies',
            name='case_studies_tag',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
