# Generated by Django 5.1.4 on 2024-12-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0029_case_studies_case_studies_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice_area',
            name='det',
            field=models.CharField(max_length=300),
        ),
    ]
