# Generated by Django 5.1.4 on 2024-12-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0030_alter_practice_area_det'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice_area',
            name='det',
            field=models.CharField(max_length=1000),
        ),
    ]
