# Generated by Django 5.1.4 on 2024-12-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0031_alter_practice_area_det'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_area',
            name='image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
