# Generated by Django 5.1.4 on 2024-12-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0032_practice_area_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice_area',
            old_name='det',
            new_name='Practice_Area_det',
        ),
        migrations.RenameField(
            model_name='practice_area',
            old_name='image',
            new_name='Practice_Area_image',
        ),
        migrations.RenameField(
            model_name='practice_area',
            old_name='law_title',
            new_name='Practice_Area_law_title',
        ),
        migrations.RenameField(
            model_name='practice_area',
            old_name='pid',
            new_name='Practice_Area_pid',
        ),
    ]
