# Generated by Django 5.1.4 on 2024-12-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0033_rename_det_practice_area_practice_area_det_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='des',
            field=models.CharField(max_length=1500),
        ),
    ]
