# Generated by Django 5.1.4 on 2025-01-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0034_alter_blog_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=2000)),
                ('up_doc1', models.FileField(blank=True, null=True, upload_to='image/')),
            ],
        ),
    ]
