# Generated by Django 5.1.4 on 2025-01-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0035_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='types_law',
            name='image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
