# Generated by Django 5.1.4 on 2025-01-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0037_alter_blog_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types_law',
            name='detail',
            field=models.TextField(max_length=550),
        ),
    ]
