# Generated by Django 5.1.4 on 2025-01-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0038_alter_types_law_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types_law',
            name='detail',
            field=models.CharField(max_length=550),
        ),
    ]
