# Generated by Django 5.1.4 on 2025-01-18 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0039_alter_types_law_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_studies',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.case_categories'),
            preserve_default=False,
        ),
    ]
