# Generated by Django 5.1.4 on 2025-01-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0040_case_studies_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_studies',
            name='detail',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
