# Generated by Django 5.1.4 on 2025-01-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0041_case_studies_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_studies',
            name='case_studies_tag',
        ),
    ]
