# Generated by Django 5.1.5 on 2025-01-31 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0007_clients_lid'),
        ('userapp', '0043_appointment_date_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientapp.clients'),
            preserve_default=False,
        ),
    ]
