# Generated by Django 5.1.5 on 2025-02-20 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_education_options'),
        ('userapp', '0046_remove_appointment_date_remove_appointment_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='lid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.lawyer'),
        ),
    ]
