# Generated by Django 5.1.5 on 2025-02-20 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0012_messages_lawyer_name'),
        ('userapp', '0047_appointment_gender_appointment_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=15)),
                ('service', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('up_doc1', models.FileField(blank=True, null=True, upload_to='appointments/')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.clients')),
            ],
        ),
    ]
