# Generated by Django 5.1.5 on 2025-02-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0048_user_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_appointment',
            name='up_doc1',
        ),
    ]
