# Generated by Django 5.1.5 on 2025-02-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0049_remove_user_appointment_up_doc1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_appointment',
            name='userid',
        ),
    ]
