# Generated by Django 5.1.5 on 2025-02-20 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_education_options'),
        ('userapp', '0050_remove_user_appointment_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_appointment',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.lawyer'),
        ),
    ]
