# Generated by Django 5.1.4 on 2025-01-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyers',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
