# Generated by Django 5.1.4 on 2025-01-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0002_lawyers_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyers',
            name='email',
        ),
    ]
