# Generated by Django 5.1.4 on 2025-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0003_remove_lawyers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyers',
            name='age',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyers',
            name='experience',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
