# Generated by Django 5.1.4 on 2025-01-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0004_lawyers_age_lawyers_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='apponitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
            ],
        ),
    ]
