# Generated by Django 5.1.5 on 2025-02-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0005_apponitment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apponitment',
        ),
        migrations.DeleteModel(
            name='lawyers',
        ),
    ]
